version: '3.7'

services:
  app:
    build: 
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes: 
      - app:/haabit
    container_name: habbits_app
    command: npm run preview
    ports:
      - "3000:3000"
    networks:
      - habbits_network

networks:
  habbits_network:

volumes:
  app: